version: "3.2"
services:
    www:
        build: .
        container_name: php-apache
        restart: on-failure
        env_file:
            - ./.env
        depends_on:
            - db
            - composer
            - chrome
        ports:
            - ${LOCAL_IP}:80:80
            - ${LOCAL_IP}:443:443
        volumes:
            - ./www:/var/www/html
            - ./logs:/var/log/apache2
            - ./www/cache:/var/www/html/cache
            - ./www/app/logs:/var/www/html/app/logs
        networks:
            - default
    db:
        image: mysql:8
        container_name: mysql
        restart: on-failure
        command: [
            '--default_authentication_plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        ports:
            - ${LOCAL_IP}:3306:3306
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./database/dump:/docker-entrypoint-initdb.d
            - ./database/mysql:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        ports:
            - ${LOCAL_IP}:8000:80
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    composer:
        image: composer/composer
        container_name: composer
        working_dir: /var/www/html
        command: install --ignore-platform-reqs
        restart: "no"
        volumes:
            - ./www:/var/www/html
    chrome:
        build: ./chrome
        user: www-data
        cap_add:
            - SYS_ADMIN
        container_name: chrome
        working_dir: /app
        restart: on-failure
        ports:
            - ${LOCAL_IP}:8080:3000
        volumes:
            - ./www/cache:/var/www/html/cache
volumes:
    persistent:
networks:
    default: