version: "3.2"
services:
    www:
        build: .
        container_name: php-apache
        restart: on-failure
        depends_on:
            - db
            - composer
            - chrome
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:443:443
        volumes:
            - ./www:/var/www/html
            - ./logs:/var/log/apache2
            - ./www/assets/cache:/var/www/html/assets/cache
        networks:
            - default
    db:
        image: mysql
        container_name: mysql
        restart: on-failure
        ports:
            - 127.0.0.1:3306:3306
        environment:
            MYSQL_DATABASE: revisionaryapp
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./database/dump:/docker-entrypoint-initdb.d
            - ./database/mysql:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        ports:
            - 127.0.0.1:8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    composer:
        image: composer/composer
        container_name: composer
        working_dir: /var/www/html
        command: install --ignore-platform-reqs
        restart: "no"
        volumes:
            - ./www:/var/www/html
    chrome:
        build: ./chrome
        cap_add:
            - SYS_ADMIN
        container_name: chrome
        working_dir: /app
        restart: on-failure
        ports:
            - 127.0.0.1:8080:3000
        volumes:
            - ./www/assets/cache:/var/www/html/assets/cache
volumes:
    persistent:
networks:
    default: