version: "3.2"
services:
    backend:
        build: ./backend
        container_name: revisionary_php-apache
        restart: "always"
        depends_on:
            - memcached
            - database
        env_file:
            - ./.env
        ports:
            - ${LOCAL_IP}:80:80
            - ${LOCAL_IP}:443:443
        volumes:
            - ./backend/src/app:/var/www/html/app
            - ./backend/src/assets:/var/www/html/assets
            - ./backend/src/cache:/var/www/html/cache
            - ./backend/src/index.php:/var/www/html/index.php
            - ./backend/src/.htaccess:/var/www/html/.htaccess
            - ./backend/logs:/var/log/apache2
        networks:
            - backend-network

    database:
        image: mysql:latest
        container_name: revisionary_database
        restart: "on-failure"
        command: [
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--slow_query_log=ON", # Make this off when in production !!!
                "--long_query_time=2",
                "--slow_query_log_file=/var/lib/mysql/mysql/slow_queries.log",
            ]
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./database/dump:/docker-entrypoint-initdb.d
            - ./database/mysql:/var/lib/mysql
        networks:
            - backend-network

    memcached:
        image: memcached:latest
        container_name: revisionary_memcached
        restart: on-failure
        command: ["-m", "512m"]
        ports:
            - 11211:11211
        networks:
            - backend-network

    chrome:
        build: ./chrome
        user: www-data
        cap_add:
            - SYS_ADMIN
        container_name: revisionary_chrome
        restart: "unless-stopped"
        ports:
            - ${LOCAL_IP}:8080:3000
        volumes:
            - ./chrome/src:/chrome/src
            - ./backend/src/cache:/chrome/cache
        networks:
            - backend-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: revisionary_phpmyadmin
        depends_on:
            - database
        ports:
            - ${LOCAL_IP}:8000:80
        volumes:
            - ./backend/config/phpmyadmin.ini:/usr/local/etc/php/conf.d/uploads.ini
        environment:
            PMA_HOSTS: ${DB_HOST}, ${DB_CLOUD_HOST}
            PMA_PORTS: ${DB_PORT}, ${DB_CLOUD_PORT}
            PMA_VERBOSES: Docker, Cloud
        networks:
            - backend-network

    phpmemcachedadmin:
        container_name: revisionary_phpmemcachedadmin
        image: phpmemcachedadmin
        build: ./phpmemcachedadmin/phpmemcachedadmin/
        ports:
            - ${LOCAL_IP}:1200:80
        restart: unless-stopped
        depends_on:
            - memcached
        volumes:
            - ./phpmemcachedadmin/Memcache.docker.php:/var/www/localhost/htdocs/Config/Memcache.php
        networks:
            - backend-network

volumes:
    persistent:
networks:
    backend-network:
        driver: bridge
